name: pangeo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - cytoolz
  - dask=0.18.2
  - distributed=1.22.0
  - fastparquet
  - ipywidgets
  - jupyterlab
  - matplotlib
  - nb_conda_kernels
  - netcdf4
  - nomkl
  - numba
  - numcodecs
  - numpy
  - pandas
  - python-blosc
  - scipy
  - scikit-image
  - xarray
  - zict
  - zarr
  - gcsfs
  - python-graphviz
  - holoviews
  - geoviews
  - nodejs
